### ISSUE TITLE
Links don't work on technical FAQ page

### ISSUE THREAD

**Issue by bethac07** [piximi/documentation#27]
I don't think it's mission critical, because we do have the links on the right hand menu bar, but they don't work. You may need to add [section labels](https://jupyterbook.org/en/stable/content/references.html#reference-section-labels) @ErinWeisbart 

<img width="1134" alt="image" src="https://github.com/user-attachments/assets/add1b168-6947-48b4-8b93-a47c4660f4da">

**Comment by ErinWeisbart** [comment]
funny, because they worked as initially written in a local build!
should now be fixed in #21
